services:
  postgres:
    image: postgres:15
    container_name: skillswap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skillswap
      POSTGRES_USER: skillswap_user
      POSTGRES_PASSWORD: skillswap_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillswap_user -d skillswap"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  seq:
    image: datalust/seq:latest
    container_name: skillswap-seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  seq_data:

networks:
  default:
    name: skillswap-network
